name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build_and_test:
        strategy:
            matrix:
                os: [ macos-latest, ubuntu-latest ]
        runs-on: ${{ matrix.os }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
        
          - name: Set up CMake
            uses: lukka/get-cmake@latest

          # Install dependencies
          - name: Install Dependencies (Linux)
            if: runner.os == 'Linux'
            run: |
              sudo apt-get update
              sudo apt-get install -y build-essential cmake
              sudo apt-get install -y valgrind
        
          - name: Install Dependencies (macOS)
            if: runner.os == 'macOS'
            run: |
              brew update
              brew upgrade
              brew install cmake

          - name: Configure CMake
            run: cmake -B build -S .
        
          - name: Build the project
            run: cmake --build build

          - name: Run tests with Valgrind (Linux only)
            if: runner.os == 'Linux'
            run: |
              valgrind --leak-check=full --show-leak-kinds=all ./build/bin/tests/test_platform

          - name: Run tests
            run: ctest --test-dir build --output-on-failure
