name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build_and_test:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest ]
        runs-on: ${{ matrix.os }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
        
          - name: Set up CMake
            uses: lukka/get-cmake@latest

          # Install dependencies
          - name: Install Dependencies (Linux)
            if: runner.os == 'Linux'
            run: |
              sudo apt-get update
              sudo apt-get install -y build-essential cmake
        
          - name: Install Dependencies (macOS)
            if: runner.os == 'macOS'
            run: |
              brew update
              brew upgrade
              brew install cmake

          - name: Configure CMake
            run: cmake -B build -S . -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
        
          - name: Build the project
            run: cmake --build build --config Debug

          - name: Run tests
            run: ctest --test-dir build --output-on-failure
